[project]
name = "aiwaf"
version = "1.0.7"
description = "AI-driven, self-learning Web Application Firewall for Python web applications"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = "MIT"
authors = [{ name = "Aayush Gauba", email = "gauba.aayush@gmail.com" }]
classifiers = [
    "Framework :: Django",
    "Framework :: Flask",
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "numpy>2",
    "pandas>2",
    "scikit-learn>=1.6.0",
    "geoip2>=5.0",
    "packaging>=20",
    "requests>=2.30",
    "python-whois>=0.9"
]

[project.optional-dependencies]
django = [
    "Django>=5.0"
]
flask = [
    "Flask>=3.0",
    "Flask-SQLAlchemy>=3.0"
]
fastapi = [
    "fastapi>=0.100",
    "starlette>=0.30",
    "uvicorn>=0.20"
]
rust = [
    "aiwaf-rust>=0.1.6"
]

[project.scripts]
aiwaf = "aiwaf.cli:main"
aiwaf-detect = "aiwaf.cli:aiwaf_detect"
aiwaf-fast = "aiwaf.fast.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aiwaf*"]

[tool.setuptools.package-data]
"aiwaf.core" = ["geolock/*.mmdb"]
